spring:
  datasource:
    url: jdbc:mysql://211.202.74.84:13306/covenant
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      # create: Spring Boot가 실행되면 테이블을 지우고 새로 만든다. 기존의 데이터는 삭제
      # create-drop: Spring Boot가 종료되면 테이블을 삭제한다.
      # update: Entity 클래스와 DB 스키마를 비교하여 DB에 생성되지 않은 테이블, 칼럼을 추가하며 제거는 하지 않는다.
      # validate: ENTITY 클래스와 DB 스키마를 비교하여 다르면 예외를 발생ㅇ시킨다.
      # none: 아무것도 실행하지 않는다.